theme = "porcif"
template = "content_template"
home_template = "home"
code_theme = "atom-one-dark"

[hero]
name = "Fahmi Dinsefa"
tagline = "Backend Software Engineer | Rust Developer"
image = "images/fahmipp.JPG"
github_url = "https://github.com/poricf"
linkedin_url = "https://www.linkedin.com/in/poricf"
