theme = "dracula"
template = "content_template"
home_template = "home"
code_theme = "atom-one-dark"

[hero]
name = "Zaferan"
tagline = "Software engineer"
image = "here"
github_url = ""
linkedin_url = ""
